
export const defaultInfo = [
    ['SK-A-3064',  'Portrait of a Girl Dressed in Blue'],
    ['SK-A-3905',  'Portrait of Arnoldus van Rijneveld'],
    ['SK-A-406',  'Portrait of Anne of Hanover, Princess Royal and Princess of Orange, Consort of Prince William IV'],
    ['SK-A-4020',  'Portrait of a Man'],
    ['SK-A-1048',  'Portrait of Emma Jane Hodges'],
    ['SK-C-1183',  'Jacobus Govaerts (b. 1635/36],. Appointed Master of Ceremonies and Clerk of the Chapter of Antwerp in 1661.'],
    ['RP-F-F01161-N',  'Portret van twee Japanse vrouwen, met kamerschermen en dienbladen met serviesgoed'],
    ['RP-T-2005-170',  'Portret van Johan Daniël Koelman'],
    ['AK-RAK-2014-6',  'Daoist Deity'],
    ['SK-A-3779',  'Johannes Thedens (1741-1743),'],
    ['RP-T-2016-11-2',  'Wilhelmina Hillegonda Schuyt'],
    ['RP-F-F01184-AR',  'Detail van het beeld Venus Victrix door Antonio Canova'],
    ['SK-A-4342',  'Wilhelmina Carolina (Carolina; 1743-87), prinses van Oranje-Nassau, dochter van Willem IV en zuster van Willem V, als kind'],
    ['RP-P-1936-453',  'Vrouw in Galata krijgt een sluier'],
    ['RP-P-1920-2701',  'Engelse vrouw met schaartje aan ceintuur'],
    ['SK-A-2963',  'Portrait of Don Ramón Satué'],
    ['RP-T-1914-17-69',  'A Xhosa (possibly Gonaqua), chieftan’s wife with an infant on her back'],
    ['SK-A-4221',  'Portrait of a Woman'],
    ['RP-F-00-7520',  'Portret van Juliana, koningin der Nederlanden'],
    ['RP-T-00-1180',  'Portret van een vrouw met handschoenen en ketting met houder voor een bezoarsteen (?],'],
    ['BK-1975-35',  'Figure of Venus and Amor'],
    ['BK-1961-111',  'Japon van drie lagen crêpe georgette'],
    ['SK-A-3064',  'Portrait of a Girl Dressed in Blue'],
    ['BK-14649-B',  'Gown with a belt'],
    ['BK-C-1994-1',  'Portrait Bust of Johann Neudörfer the Younger'],
    ['SK-A-5049',  'Crucifixion of Christ, with the Virgin and St John'],
    ['NG-2016-50-2',  "Prentbriefkaart uit album 'Als aandenken aan Suriname'"],
    ['AK-MAK-9',  'Ritual bell'],
    ['SK-A-233',  ' Portrait of Catherine Bégon'],
];

export const defaultIds: string[] = defaultInfo.map(info => btoa(info[0]))