
export const defaultInfo = [
    {'id': 'SK-A-3064', 'Title': 'Portrait of a Girl Dressed in Blue', 'Artist': 'Johannes Cornelisz. Verspronck', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-3064.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/hpl3FiKJycePxIROjWZLZXbodT5uV-EsBw9dlux7NFmhbWAX2xtHQZmlIqb9yxhu-yvs28KQsw1ulzjL8qdiRhPmDgc=s0', 'Culture': 'dutch', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-3064', 'Museum': 'rijks'}, 
    {'id': 'SK-A-3905', 'Title': 'Portrait of Arnoldus van Rijneveld', 'Artist': 'Louis Tocqué', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-3905.jpg', 'Image_Url': 'https://lh3.ggpht.com/HlWkEKGY2JJkr2tJhOMpQCrul9A6hXm-oZJdszsmVBGSedOhEjplgOYHxbiEE7x1RT32t_DVPLqqpx4f7KD25x4aiMvN=s0', 'Culture': 'french', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-3905', 'Museum': 'rijks'}, 
    {'id': 'SK-A-406', 'Title': 'Portrait of Anne of Hanover, Princess Royal and Princess of Orange, Consort of Prince William IV', 'Artist': 'Johann Valentin Tischbein', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-406.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/7R_jTdiJvKktzF2Emce-CNuh8eAeNwWZrI2l9U7GfkjONz0Oqvmu6ShVzrnj4B-zSCuXOMfBT4R8Zx5LWStJM-6Ing=s0', 'Culture': 'german', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-406', 'Museum': 'rijks'}, 
    {'id': 'SK-A-4020', 'Title': 'Portrait of a Man', 'Artist': 'Niccolò Cassana', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-4020.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/XX1fKtBM94RKIIZN0hw0T6VB0nz660FLMiJPMN7e75zG6eIPUdUVDZbSb4GifaISlNzPICUl1Q_CyyzRSQUed6Ybww=s0', 'Culture': 'italian', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-4020', 'Museum': 'rijks'}, 
    {'id': 'SK-A-1048', 'Title': 'Portrait of Emma Jane Hodges', 'Artist': 'Charles Howard Hodges', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-1048.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/Kl8AXr5AhNC76x_bXyfGD-FiERqUUWD8DuMp11ba1MxgdDgnunBrqblz2__5as-knsJgW0NMwvFgbP0toj1hxL_bHg=s0', 'Culture': 'british', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-1048', 'Museum': 'rijks'}, 
    {'id': 'SK-C-1183', 'Title': 'Jacobus Govaerts (b. 1635/36). Appointed Master of Ceremonies and Clerk of the Chapter of Antwerp in 1661.', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-C-1183.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/a1nSuhDhdWFS-OHTaYzandG8D5GescXdtcTXV1Ka0Zc-i9jLZ5jHGnSrUXxt6xBtnnDw2oxBuqB1ZT7QQOeBs3eDLYI=s0', 'Culture': 'belgian', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-C-1183', 'Museum': 'rijks'}, 
    {'id': 'RP-F-F01161-N', 'Title': 'Portret van twee Japanse vrouwen, met kamerschermen en dienbladen met serviesgoed', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-F-F01161-N.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/mjviEnHTuK-f2oNCdxDUZkwyo2r_ozBzbdGarMKEQV7B8QsHlwiqxdXbcfqRS760oTr10waggFj1DSVpAOYz6W_4T-E=s0', 'Culture': 'japanese', 'Classification': 'uncategorized', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-F-F01161-N', 'Museum': 'rijks'}, 
    {'id': 'RP-T-2005-170', 'Title': 'Portret van Johan Daniël Koelman', 'Artist': 'Eastman Johnson', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-T-2005-170.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/FL9OGjSTUsYzlhjUiHWeVpf2QqCjQ8vkqMoBA4ne5VlT2XH0NFF0L7iPumUMvtRyG72yo23jMw3veFipcynk-nXM8hmg=s0', 'Culture': 'american', 'Classification': 'drawings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-T-2005-170', 'Museum': 'rijks'}, 
    {'id': 'AK-RAK-2014-6', 'Title': 'Daoist Deity', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/AK-RAK-2014-6.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/sMLjzu7fs4UriklahCjKCzRJX5MzJoKr77LUkRGWLztpkd3N_Oc9Z8hW86LYQEx2TN7ynW3QlYEt0kFe5Mjfqu5rNL2F=s0', 'Culture': 'chinese', 'Classification': 'uncategorized', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/AK-RAK-2014-6', 'Museum': 'rijks'}, 
    {'id': 'SK-A-3779', 'Title': 'Johannes Thedens (1741-1743)', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-3779.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/H6IKGamgE40L_r0NA1lvnMF5Ujdhp9a2tIXOfYXMTkRbuVFvd1OHHAK3zamkL629n3Uil_ABgdXNoUMVvE5sy7cJdrg=s0', 'Culture': 'southeast asian', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-3779', 'Museum': 'rijks'}, 
    {'id': 'RP-T-2016-11-2', 'Title': 'Wilhelmina Hillegonda Schuyt', 'Artist': 'Jean-Etienne Liotard', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-T-2016-11-2.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/2HxJdHLOIcDB8bzOMcxRA29Nr3uRwqNubq1aBZw1Ume4H93N3R3OrSJKNo9BunDLxAzu1XvzShEEQKBS79eKhqzsfA=s0', 'Culture': 'european (general)', 'Classification': 'drawings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-T-2016-11-2', 'Museum': 'rijks'}, 
    {'id': 'RP-F-F01184-AR', 'Title': 'Detail van het beeld Venus Victrix door Antonio Canova', 'Artist': 'Alinari', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-F-F01184-AR.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/vSQCCuvp4OxAVNeIgAQhiG9HLqWs-VGtvHcUbawzCDz6FIa617my0lWNUIh9hnN_0qpG5kXzhwK2NKzNJ7dMg7OoKVM=s0', 'Culture': 'roman', 'Classification': 'uncategorized', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-F-F01184-AR', 'Museum': 'rijks'}, 
    {'id': 'SK-A-4342', 'Title': 'Wilhelmina Carolina (Carolina; 1743-87), prinses van Oranje-Nassau, dochter van Willem IV en zuster van Willem V, als kind', 'Artist': 'Robert Mussard', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-4342.jpg', 'Image_Url': 'https://lh4.ggpht.com/Rs4bJVaBPiWax03DZ6G0sWHRiEcFjKOpLcHoWdAmlef7oLmZCc1MH_HLl_g1YWxs8MDLqtIn4Dcd78IWXtDZclRFPQ=s0', 'Culture': 'swiss', 'Classification': 'uncategorized', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-4342', 'Museum': 'rijks'}, 
    {'id': 'RP-P-1936-453', 'Title': 'Vrouw in Galata krijgt een sluier', 'Artist': 'Jean-Etienne Liotard', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-P-1936-453.jpg', 'Image_Url': 'https://lh6.ggpht.com/C3yI529DQKscBkxlFLMR68zA1jf_AIPwB2TedjINA3douOFW1PGh6eIVyqi1vJ8uvgo5uhGjcmaHkzoipbHkMj-T8mc=s0', 'Culture': 'austrian', 'Classification': 'prints', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-P-1936-453', 'Museum': 'rijks'},
    {'id': 'RP-P-1920-2701', 'Title': 'Engelse vrouw met schaartje aan ceintuur', 'Artist': 'Wenceslaus Hollar', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-P-1920-2701.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/X31xIWJh6ERGN51s8yJPL_Cgdu-XKxr9TqXBVProfWYMgaJfQaHlvBFlWgLw5GU4c4wTWdcGWC4XA1m2Fs_g-uLurbM=s0', 'Culture': 'czech', 'Classification': 'prints', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-P-1920-2701', 'Museum': 'rijks'}, 
    {'id': 'SK-A-2963', 'Title': 'Portrait of Don Ramón Satué', 'Artist': 'Francisco de Goya', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-2963.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/SwwiVAxnwFE_s-k7-bPOZ6jnGfcuVDJoZ-ofLb0Zispb-mJdsfasrE1nTPRcGDPwyEqY0txKpjPcAWaIIltYvvPtDA8=s0', 'Culture': 'spanish', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-2963', 'Museum': 'rijks'}, 
    {'id': 'RP-T-1914-17-69', 'Title': 'A Xhosa (possibly Gonaqua) chieftan’s wife with an infant on her back', 'Artist': 'Robert Jacob Gordon', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-T-1914-17-69.jpg', 'Image_Url': 'https://lh5.ggpht.com/8KFthngOv0FyWw2_xhgeIRQZ4MXGncWtGjDXRV49n-HNl_jR3Zdfz_ci7N-e9J6g33Cz5toIYu0cMRd5HcO17CvrLUs=s0', 'Culture': 'various', 'Classification': 'drawings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-T-1914-17-69', 'Museum': 'rijks'}, 
    {'id': 'SK-A-4221', 'Title': 'Portrait of a Woman', 'Artist': 'Pieter Dubordieu', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-4221.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/NlI339xx7vCw_Pi0AJFwt2YHlS4v9eBloZsJonKkIbQkANyxT-cR1QpRvBRdAoWHdutDvxQWbH2dGcaQ1SLmaTb5O9s=s0', 'Culture': 'various', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-4221', 'Museum': 'rijks'}, 
    {'id': 'RP-F-00-7520', 'Title': 'Portret van Juliana, koningin der Nederlanden', 'Artist': 'Franz Ziegler', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-F-00-7520.jpg', 'Image_Url': 'https://lh6.ggpht.com/5neJQDzidt0v54Ogv72Zl8ED-AJY9FSd540v6UUBBvJTkH1SixL1EMnURY2LU47_yJaEui8S12gDV-8YzpbINhvpr90=s0', 'Culture': 'dutch', 'Classification': 'prints', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-F-00-7520', 'Museum': 'rijks'}, 
    {'id': 'RP-T-00-1180', 'Title': 'Portret van een vrouw met handschoenen en ketting met houder voor een bezoarsteen (?)', 'Artist': 'Jan Gerard Waldorp', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/RP-T-00-1180.jpg', 'Image_Url': 'https://lh6.ggpht.com/Em5WXOEwwj7UzaLFPoo4GZVZZsu7uTE3n9n6bxlCO9iCqJAvmR59S1mP1ichpmJAdOxoGjWHPNh6PAKlbTgQQVmVDw=s0', 'Culture': 'dutch', 'Classification': 'drawings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/RP-T-00-1180', 'Museum': 'rijks'}, 
    {'id': 'BK-1975-35', 'Title': 'Figure of Venus and Amor', 'Artist': 'Porzellanmanufaktur Frankenthal', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/BK-1975-35.jpg', 'Image_Url': 'https://lh6.ggpht.com/xGRd7rGQNHkDMoUg0JiXYkDU9ghiG2Q60Zof_iuuOuYjGNwRoOzwpVrqLDkRPIDlt-wNpzi9sncCIzDh_Ltx71n3SDQ=s0', 'Culture': 'various', 'Classification': 'ceramics', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/BK-1975-35', 'Museum': 'rijks'}, 
    {'id': 'BK-1961-111', 'Title': 'Japon van drie lagen crêpe georgette', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/BK-1961-111.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/b2zUtI2tCBGAzYWoxZXUz5tLTPlf7d8s_RSza_TGyBR3dnfpmNF9KUezLHzuywM491NF0uDWyKOPmX09fMgMeaZRROA=s0', 'Culture': 'dutch', 'Classification': 'textiles', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/BK-1961-111', 'Museum': 'rijks'}, 
    {'id': 'SK-A-3064', 'Title': 'Portrait of a Girl Dressed in Blue', 'Artist': 'Johannes Cornelisz. Verspronck', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-3064.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/hpl3FiKJycePxIROjWZLZXbodT5uV-EsBw9dlux7NFmhbWAX2xtHQZmlIqb9yxhu-yvs28KQsw1ulzjL8qdiRhPmDgc=s0', 'Culture': 'dutch', 'Classification': 'paintings', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-3064', 'Museum': 'rijks'}, 
    {'id': 'BK-14649-B', 'Title': 'Gown with a belt', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/BK-14649-B.jpg', 'Image_Url': 'https://lh3.ggpht.com/swH028bJIxWjCKuXIWNAvXCK_fTZAbf8VUOVs45xKmaK5MWbaY0ygA7sk9dTsP0ckbta7yB-bsmCjMda9GDn5i51Rd8=s0', 'Culture': 'dutch', 'Classification': 'accessories', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/BK-14649-B', 'Museum': 'rijks'}, 
    {'id': 'BK-C-1994-1', 'Title': 'Portrait Bust of Johann Neudörfer the Younger', 'Artist': 'Johan Gregor van der Schardt', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/BK-C-1994-1.jpg', 'Image_Url': 'https://lh3.ggpht.com/I61N1EPqLn0wUWDLrEEJHhWQ5Xm5LPdgoZXn_DXs4c02DfZCbn0XoSdwpWxh7aEPFeeY-CvODrBzgnXghQKZZEs5sA=s0', 'Culture': 'dutch', 'Classification': 'sculptures', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/BK-C-1994-1', 'Museum': 'rijks'}, 
    {'id': 'SK-A-5049', 'Title': 'Crucifixion of Christ, with the Virgin and St John', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-5049.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/ABSdTs6_zVXat-Kr8bSpudXG0fezqu_b1Jsu5UOkuO9OOakCtJNI-pTkzq9OBhDKP6_b1AjU4ikjgldi36t4jy2TF4Q=s0', 'Culture': 'various', 'Classification': 'glass', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-5049', 'Museum': 'rijks'}, 
    {'id': 'NG-2016-50-2', 'Title': "Prentbriefkaart uit album 'Als aandenken aan Suriname'", 'Artist': 'diverse vervaardigers', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/NG-2016-50-2.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/uZ19VM2BnCRfgFys5hGvlK6QQapkZpjwPdgSLnNMToSaWPxSPyDoDTQdLRSJ5cW0z6Sj0sjS0kd4etLaddLmaRdNsv8V=s0', 'Culture': 'various', 'Classification': 'paper', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/NG-2016-50-2', 'Museum': 'rijks'}, 
    {'id': 'AK-MAK-9', 'Title': 'Ritual bell', 'Artist': 'anonymous', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/AK-MAK-9.jpg', 'Image_Url': 'https://lh3.googleusercontent.com/dKf0LOpYAbbrgwyYp_G3A7ptyQIZH-LTTHD_NjbYqotsUIJGgHwflvV42BcqXGDeEntwyWcrCNIYhdzxxr-Kt7e3RwUT=s0', 'Culture': 'chinese', 'Classification': 'musical instruments', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/AK-MAK-9', 'Museum': 'rijks'}, 
    {'id': 'SK-A-233', 'Title': ' Portrait of Catherine Bégon', 'Artist': 'Jean-Etienne Liotard', 'Thumbnail_Url': 'https://mmlsparkdemo.blob.core.windows.net/rijks/resized_images/SK-A-233.jpg', 'Image_Url': 'https://lh5.ggpht.com/YTG7ut9lcJ6UjZpsG3GCq7-LwZTKw2lPvegDUOaMTDsbFuVJ1SEQZOnoy9ZfcbPy-1zHjoK0Jn7TmrGGMsmlap9_-oA=s0', 'Culture': 'various', 'Classification': 'uncategorized', 'Museum_Page': 'https://www.rijksmuseum.nl/en/collection/SK-A-233', 'Museum': 'rijks'}
];

export const defaultIds: string[] = defaultInfo.map(info => btoa(info['id']))